name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: direnv version

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        direnv:
          - 2.23.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: macOS coreutils # needed by bats-core
        if: matrix.os == 'macos-latest'
        run: brew install coreutils

      - name: Install bats-core
        run: |
          git clone --depth 1 --branch v1.6.0 https://github.com/bats-core/bats-core.git $HOME/bats-core
          echo "$HOME/bats-core/bin" >>"$GITHUB_PATH"

      - name: Run tests
        run: |
          asdf plugin-add direnv $GITHUB_WORKSPACE
          asdf install direnv ${{ matrix.direnv }}
          asdf global direnv ${{ matrix.direnv }}
          make test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: make lint

  format:
    # ubuntu-latest is still pinned to Ubuntu 20, which doesn't have `shfmt`
    # available to easily install.
    # TODO: switch back to ubuntu-latest once Ubuntu 22 is the default.
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install shfmt
        run: sudo apt-get install -y shfmt

      - name: Run shfmt
        run: make fmt-check
