name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: direnv version

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        direnv:
          - 2.23.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: macOS coreutils # needed by bats-core
        if: matrix.os == 'macos-latest'
        run: brew install coreutils

      - name: Install bats-core
        run: |
          git clone --depth 1 --branch v1.1.0 https://github.com/bats-core/bats-core.git $HOME/bats-core
          echo "$HOME/bats-core/bin" >>"$GITHUB_PATH"

      - name: Run tests
        run: |
          asdf plugin-add direnv $GITHUB_WORKSPACE
          asdf install direnv ${{ matrix.direnv }}
          asdf global direnv ${{ matrix.direnv }}
          bats test

  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Run ShellCheck
        run: shellcheck bin/* lib/commands/*

  format:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shfmt
        run: brew install shfmt

      - name: Run shfmt
        run: shfmt -d -i 2 -ci .
